# Generated by Django 3.0.4 on 2020-03-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=264, null=True)),
                ('content', models.CharField(max_length=264, null=True)),
                ('course_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v_learn.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=264)),
                ('option_a', models.CharField(max_length=264)),
                ('option_b', models.CharField(max_length=264)),
                ('option_c', models.CharField(max_length=264)),
                ('option_d', models.CharField(max_length=264)),
                ('right_option', models.CharField(max_length=264)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_learn.Course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_learn.Topic')),
            ],
        ),
    ]
