# Generated by Django 3.0.4 on 2020-04-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_learn', '0002_auto_20200327_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlearnUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=264)),
                ('courseList', models.CharField(max_length=264)),
                ('percentage', models.CharField(max_length=264)),
            ],
        ),
    ]
