# Generated by Django 3.0.4 on 2020-04-04 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_learn', '0005_auto_20200403_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v_learn.Course'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_a',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_b',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_c',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_d',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='right_option',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v_learn.Topic'),
        ),
    ]
